version: '3'
services:
  nginx:
    container_name: my-nginx
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf_local.d:/etc/nginx/conf.d
    depends_on:
    - app

  postgresql:
    image: postgres:13
    container_name: my-postgresql
    environment:
      - POSTGRES_DB=schedule_board
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "55432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d

  app:
    container_name: app
    restart: always
    build: ./schedule-board
    working_dir: /schedule-board
    ports:
    - 8080:8080
    # depends_on:
    links:
    - postgresql
