version: '3'
services:
  nginx:
    container_name: my-nginx
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
    - app

  postgresql:
    image: postgres:13
    container_name: my-postgresql
    environment:
      - POSTGRES_DB=schedule_board
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d

  app:
    restart: always
    build: ./schedule-board
    working_dir: /schedule-board
    volumes:
      - ./schedule-board:/schedule-board
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - postgresql
