spring:
  # DB接続先設定
  datasource:
    # localの場合
    # url : jdbc:postgresql://localhost:5432/schedule_board
    # docker-composeの場合
    url : jdbc:postgresql://postgresql:5432/schedule_board
    username : postgres
    password : postgres
    driver-class-name : org.postgresql.Driver
  # アプリ起動時にテーブル初期化
  # docker-composeの場合、使用しない
  # sql:
  #   init:
  #     mode: never
  #     schema-locations: classpath:schema.sql
  #     data-locations: classpath:data.sql
  #     encoding: utf-8
  # hibername設定
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    show-sql : false
    hibernate.ddl-auto : none

    