spring:
  # DB接続先設定
  datasource:
    # rds利用
    url : jdbc:postgresql://schedule-board-ecs.cgb3wdsrhbsj.ap-northeast-1.rds.amazonaws.com:5432/schedule_board
    username : postgres
    password : EnZGxZLduq4t
    driver-class-name : org.postgresql.Driver
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: utf-8
  # hibername設定
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    show-sql : false
    hibernate.ddl-auto : none

    